version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: 'http://localhost:8000/'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    # command: uvicorn app.main:app --host 0.0.0.0 --port 80
    command: ./start.sh
    ports:
      - 8000:80
    depends_on:
      migrator:
        condition: service_completed_successfully

  migrator:
    build: ./backend
    command: "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fast_api_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fast_api_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  pgdata:
    driver: local