version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fast_api_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local