"""v2

Revision ID: 306cb1cf6daa
Revises: 052bfaf042c8
Create Date: 2025-04-10 18:07:20.475558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306cb1cf6daa'
down_revision: Union[str, None] = '052bfaf042c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charsproducttyperelation',
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('producttype_art', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['characteristics.id'], ),
    sa.ForeignKeyConstraint(['producttype_art'], ['producttypes.art'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charsproducttyperelation')
    # ### end Alembic commands ###
