"""cascade delete producttypes

Revision ID: 3533d23606d2
Revises: bc9373e040af
Create Date: 2025-04-22 01:25:47.939658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3533d23606d2'
down_revision: Union[str, None] = 'bc9373e040af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('charsproducttyperelation_producttype_art_fkey', 'charsproducttyperelation', type_='foreignkey')
    op.drop_constraint('charsproducttyperelation_char_id_fkey', 'charsproducttyperelation', type_='foreignkey')
    op.create_foreign_key(None, 'charsproducttyperelation', 'producttypes', ['producttype_art'], ['art'], ondelete='CASCADE')
    op.create_foreign_key(None, 'charsproducttyperelation', 'characteristics', ['char_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('producttypes_product_id_fkey', 'producttypes', type_='foreignkey')
    op.create_foreign_key(None, 'producttypes', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producttypes', type_='foreignkey')
    op.create_foreign_key('producttypes_product_id_fkey', 'producttypes', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'charsproducttyperelation', type_='foreignkey')
    op.drop_constraint(None, 'charsproducttyperelation', type_='foreignkey')
    op.create_foreign_key('charsproducttyperelation_char_id_fkey', 'charsproducttyperelation', 'characteristics', ['char_id'], ['id'])
    op.create_foreign_key('charsproducttyperelation_producttype_art_fkey', 'charsproducttyperelation', 'producttypes', ['producttype_art'], ['art'])
    # ### end Alembic commands ###
