"""v2.3

Revision ID: 83cb1d2534d9
Revises: c093d4891ec3
Create Date: 2025-04-10 18:32:47.042151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cb1d2534d9'
down_revision: Union[str, None] = 'c093d4891ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('characteristics_producttype_art_fkey', 'characteristics', type_='foreignkey')
    op.drop_column('characteristics', 'producttype_art')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristics', sa.Column('producttype_art', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('characteristics_producttype_art_fkey', 'characteristics', 'producttypes', ['producttype_art'], ['art'])
    # ### end Alembic commands ###
